name: flutter_application_1
description: "Covai E-Auction - A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  share_plus: ^12.0.1
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  workmanager: 0.9.0+3
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - asset/images/logo.jpeg
    - asset/images/call.png
    - asset/images/whatapp.jpg
    - asset/images/share.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "asset/images/logo.jpeg"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "asset/images/logo.jpeg"
    background_color: "#002366"
    theme_color: "#002366"
  windows:
    generate: true
    image_path: "asset/images/logo.jpeg"
  macos:
    generate: true
    image_path: "asset/images/logo.jpeg"